# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm
      run: |
        npm install
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: cleandevcode/material-kit-react@master
      with:
          name: cleandevcode/material-kit-react/my-app
          registry: docker.pkg.github.com
          username: ${{ secrets.CLEANDEVCODE }}
          password: ${{ secrets.cleandevcode }}
          dockerfile: Dockerfile-prod
          tags: latest
